-------------------------------------------------------------------------------
Test set: com.miniups.service.UserServiceTest
-------------------------------------------------------------------------------
Tests run: 23, Failures: 3, Errors: 0, Skipped: 0, Time elapsed: 7.852 s <<< FAILURE! -- in com.miniups.service.UserServiceTest
com.miniups.service.UserServiceTest.testBatchOperations -- Time elapsed: 0.005 s <<< FAILURE!
org.opentest4j.AssertionFailedError: expected: <1> but was: <0>
	at org.junit.jupiter.api.AssertionFailureBuilder.build(AssertionFailureBuilder.java:151)
	at org.junit.jupiter.api.AssertionFailureBuilder.buildAndThrow(AssertionFailureBuilder.java:132)
	at org.junit.jupiter.api.AssertEquals.failNotEqual(AssertEquals.java:197)
	at org.junit.jupiter.api.AssertEquals.assertEquals(AssertEquals.java:150)
	at org.junit.jupiter.api.AssertEquals.assertEquals(AssertEquals.java:145)
	at org.junit.jupiter.api.Assertions.assertEquals(Assertions.java:531)
	at com.miniups.service.UserServiceTest.testBatchOperations(UserServiceTest.java:364)
	at java.base/java.lang.reflect.Method.invoke(Method.java:569)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)

com.miniups.service.UserServiceTest.testNullHandling -- Time elapsed: 0.003 s <<< FAILURE!
org.opentest4j.AssertionFailedError: Unexpected exception type thrown, expected: <java.lang.IllegalArgumentException> but was: <com.miniups.exception.UserNotFoundException>
	at org.junit.jupiter.api.AssertionFailureBuilder.build(AssertionFailureBuilder.java:151)
	at org.junit.jupiter.api.AssertThrows.assertThrows(AssertThrows.java:67)
	at org.junit.jupiter.api.AssertThrows.assertThrows(AssertThrows.java:35)
	at org.junit.jupiter.api.Assertions.assertThrows(Assertions.java:3115)
	at com.miniups.service.UserServiceTest.testNullHandling(UserServiceTest.java:373)
	at java.base/java.lang.reflect.Method.invoke(Method.java:569)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
Caused by: com.miniups.exception.UserNotFoundException: 用户 'null' 不存在
	at com.miniups.service.UserService.getCurrentUserInfo(UserService.java:73)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:569)
	at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:354)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.invokeJoinpoint(ReflectiveMethodInvocation.java:196)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:768)
	at org.springframework.transaction.interceptor.TransactionInterceptor$1.proceedWithInvocation(TransactionInterceptor.java:123)
	at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:392)
	at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:119)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:184)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:768)
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:720)
	at com.miniups.service.UserService$$SpringCGLIB$$0.getCurrentUserInfo(<generated>)
	at com.miniups.service.UserServiceTest.lambda$testNullHandling$7(UserServiceTest.java:374)
	at org.junit.jupiter.api.AssertThrows.assertThrows(AssertThrows.java:53)
	... 6 more

com.miniups.service.UserServiceTest.testUpdateUser_EmailExists -- Time elapsed: 0.009 s <<< FAILURE!
Wanted but not invoked:
userRepository bean.existsByEmailAndIdNot(
    "admin@example.com",
    1L
);
-> at com.miniups.service.UserServiceTest.testUpdateUser_EmailExists(UserServiceTest.java:209)

However, there were exactly 3 interactions with this mock:
userRepository bean.findById(1L);
-> at com.miniups.service.UserService.updateUser(UserService.java:141)

userRepository bean.existsByEmail(
    "admin@example.com"
);
-> at com.miniups.service.UserService.updateUser(UserService.java:152)

userRepository bean.save(
    com.miniups.model.entity.User@3d67ae7c
);
-> at com.miniups.service.UserService.updateUser(UserService.java:182)


	at com.miniups.service.UserServiceTest.testUpdateUser_EmailExists(UserServiceTest.java:209)
	at java.base/java.lang.reflect.Method.invoke(Method.java:569)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)

